version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://mysql.railway.internal:3306/railway
      DB_USER: root
      DB_PASS: ZQuJSPpyiHZMymdLCYFxsQiOQPBZafUv

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: ZQuJSPpyiHZMymdLCYFxsQiOQPBZafUv
    ports:
      - "3306:3306"
