version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/pharmacystoredb
      DB_USER: root
      DB_PASS: root

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: pharmacystoredb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
